//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره پروشا.
        /// </summary>
        public static string AboutProsha {
            get {
                return ResourceManager.GetString("AboutProsha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار و مقالات.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست مطالب وبلاگ.
        /// </summary>
        public static string BlogContentList {
            get {
                return ResourceManager.GetString("BlogContentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی جامع.
        /// </summary>
        public static string ComprehensiveSupport {
            get {
                return ResourceManager.GetString("ComprehensiveSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلیه حقوق این سایت متعلق به گروه نرم افزاری پروشا می باشد. طراحی وب سایت توسط.
        /// </summary>
        public static string DevelopByZavosh {
            get {
                return ResourceManager.GetString("DevelopByZavosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویژگی های.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقالات و اخبار.
        /// </summary>
        public static string HomeArticle {
            get {
                return ResourceManager.GetString("HomeArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مطالب وبلاگ.
        /// </summary>
        public static string LatestArticles {
            get {
                return ResourceManager.GetString("LatestArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدیدترین اخبار و مقالات در حوزه نرم افزار های پخش را می توانید از بخش وبلاگ پروشا دنبال نمایید..
        /// </summary>
        public static string LatestArticlesTitle {
            get {
                return ResourceManager.GetString("LatestArticlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر محصولات.
        /// </summary>
        public static string OtherProducts {
            get {
                return ResourceManager.GetString("OtherProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی POS.
        /// </summary>
        public static string PosSupport {
            get {
                return ResourceManager.GetString("PosSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت تعریف داینامیک کمپین های نظرسنجی و تحقیقات بازار با فرمت دلخواه توسط شرکت های پخش و تامین کنندگان و ارسال آن بر روی اپلیکیشن مشتریان
        ///											ارتقاء به عملکرد پرسنل و شرکت های پخش از طریق نتایج حاصل شده از گزارشات تحلیل بازار و بازخورد مشتریان.
        /// </summary>
        public static string ProductDesc {
            get {
                return ResourceManager.GetString("ProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه نرم افزاری پروشا.
        /// </summary>
        public static string Prosha {
            get {
                return ResourceManager.GetString("Prosha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه نرم افزاری پروشا.
        /// </summary>
        public static string ProshaCompany {
            get {
                return ResourceManager.GetString("ProshaCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادامه مطلب.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل خود را ثبت کنید.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرسنجی و تحقیقات بازار.
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتراک گذاری این مقاله.
        /// </summary>
        public static string ShareArticle {
            get {
                return ResourceManager.GetString("ShareArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده امکانات.
        /// </summary>
        public static string ShowFeatures {
            get {
                return ResourceManager.GetString("ShowFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده محصول.
        /// </summary>
        public static string ShowProduct {
            get {
                return ResourceManager.GetString("ShowProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول ویژه.
        /// </summary>
        public static string SpecialProduct {
            get {
                return ResourceManager.GetString("SpecialProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر خود را ثبت نمایید.
        /// </summary>
        public static string SubmitComment {
            get {
                return ResourceManager.GetString("SubmitComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عضویت در خبر نامه پروشا از آخرین اخبار صنعت پخش مطلع شوید.
        /// </summary>
        public static string SubscribeNewsletter {
            get {
                return ResourceManager.GetString("SubscribeNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر شما با موفقیت ثبت گردید و پس از تایید مدیر سایت در همین صفحه نمایش داده خواهد شد..
        /// </summary>
        public static string SuccessSubmitComment {
            get {
                return ResourceManager.GetString("SuccessSubmitComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقالات پیشنهادی.
        /// </summary>
        public static string SuggestedArticles {
            get {
                return ResourceManager.GetString("SuggestedArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپلیکیشن POS، رویایی که محقق شد..
        /// </summary>
        public static string TopFooter {
            get {
                return ResourceManager.GetString("TopFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روز باشید.
        /// </summary>
        public static string UpDate {
            get {
                return ResourceManager.GetString("UpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازدید.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات کاری.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر شما.
        /// </summary>
        public static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زاوش.
        /// </summary>
        public static string Zavosh {
            get {
                return ResourceManager.GetString("Zavosh", resourceCulture);
            }
        }
    }
}
